# Air configuration for hot reload
root = "."

[build]
  cmd = "go run ./cmd/server"
  bin = "tmp/main"
  include_ext = [".go", ".tpl", ".tmpl", ".html"]
  exclude_dir = ["pb", "tmp"]
  exclude_file = []
  follow_symlink = true
  delay = 1000 # ms

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta" 